_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "models/vit_base_patch16_clip_224_openai.pkl"
  MASK_ON: False
  BACKBONE:
    NAME: build_vit_fpn_backbone
  VIT:
    PATCH_SIZE: 16
    DEPTH: 12 
    NUM_HEADS: 12
    EMBED_DIM: 768
    DROP_PATH_RATE: 0.1
    IN_FEATURES: ["vit"]
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  OPTIMIZER: "ADAMW"