_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: False
  WEIGHTS:
    "models/convnext_tiny_1k_224_ema.pkl"
  BACKBONE:
    NAME: "build_convnext_fpn_backbone"
  CONVNEXT:
    DEPTHS: [3, 3, 9, 3]
    DIMS: [96, 192, 384, 768]
    DROP_PATH_RATE: 0.2
    LAYER_SCALE_INIT_VALUE: 1e-6
    OUT_FEATURES: [0, 1, 2, 3]
  FPN:
    IN_FEATURES: [0, 1, 2, 3]
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  OPTIMIZER: "ADAMW"
  BASE_LR: 0.0001
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
OUTPUT_DIR: "training_dir/convnext_t_fasterrcnn"