MODEL:
  META_ARCHITECTURE: "OneStageDetector"
  WEIGHTS: "models/convnext_tiny_1k_224_ema.pkl"
  BACKBONE:
    NAME: "build_convnext_fpn_backbone"
    ADAPTER:
      MODE: "dp"
  CONVNEXT:
    DEPTHS: [3, 3, 9, 3]
    DIMS: [96, 192, 384, 768]
    DROP_PATH_RATE: 0.2
    LAYER_SCALE_INIT_VALUE: 1e-6
    OUT_FEATURES: [0, 1, 2, 3]
  FPN:
    IN_FEATURES: [0, 1, 2, 3]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  # PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  FCOS:
    IN_FEATURES : ["p2", "p3", "p4", "p5", "p6"]
    FPN_STRIDES : [4, 8, 16, 32, 64]
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001  # Note that RetinaNet uses a different default learning rate
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  OPTIMIZER: "ADAMW"
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
TEST: 
  EVAL_PERIOD: 10000
OUTPUT_DIR: "training_dir/fcos_convnext_t_3x_dp"