_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: ""
  MASK_ON: False
  BACKBONE:
    ADAPTER:
        MODE: "ft"
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
    NORM: "BN"
  ROI_HEADS:
    NUM_CLASSES: 20
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval', 'voc_2012_trainval')
  TEST: ('voc_2007_test',)
SOLVER:
  STEPS: (24000, 32000)
  MAX_ITER: 36000  # 17.4 epochs
  WARMUP_ITERS: 200
TEST: 
  EVAL_PERIOD: 1000